# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lowella
email: meetlowella@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lowella's goal is to build stronger relationships that last using kindness, love, trust and technology. 
  By applying advanced data analysis and current psychological concepts, Lowella is decoding intimacy.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://lowella.com" # the base hostname & protocol for your site
twitter_username: "@wardsorrick"
github_username:  "intimattic"

# Build settings
markdown: kramdown
